### ISSUE TITLE
Date attribute doesn't do anything.

### ISSUE THREAD

**Issue by frankjonen** [iainc/iA-Writer-Templates#60] opened 2022-12-25 18:25 UTC
I have the below setup so the autofill from `data-document` doesn't erase the span.
The only way I can get `data-date` to actually do something is if I put it into the markdown file. Which defeats the purpose.

```HTML
<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" media="all" href="style.css">
</head>

<body>
	<span data-date="d.MMMM YYYY"></span>
	<div data-document>
	<\div>
</body>

</html>
```

**Comment by frankjonen** [comment] 2022-12-26 00:45
So it only does nothing when in HTML preview. It works in PDF mode now. So half-bug then.

**Comment by antons** [comment] 2023-01-05 06:31
Thank you for reporting the issue! Closing as duplicate of #59.

**Closed by antons** 2023-01-05 06:31 UTC
Labels: Duplicate
